### ISSUE TITLE
[Help Wanted] Shadow Acne

### ISSUE THREAD

**Issue by zznewclear13** [cs87-dartmouth/darts-2022#1]
Hi,

First of all, thank you for sharing your slides! They benefit me a lot. I am not enrolled in the course, so I think this might be the only way to ask for help.

I have shadow acne problem in my rendering below. I have read Ray Tracing in One Weekend already, but it only shows that we can get rid of shadow acne by setting a minimum hitting distance `t=0.001`, which we already have in our `Ray.h`(`epsilon=0.0001` by default).
![01_recursive_raytracing](https://user-images.githubusercontent.com/57306674/191409656-95cc28a3-e9e5-4c22-bc98-2e2e5678262f.png)

Therefore I reflected on my implementation and have some questions. When we create new Lambertian reflection ray, should we normalize its direction vector? If we do not normalize it, its length can be really small, and when the ray hits surface, the hit distance can be very large (>0.0001). However I already tried to normalize it, turned out it didn't help.

The only plausible solution I found is to offset hit point by `hit normal * epsilon`, but it is not listed in our slides. I drew a diagram below, hope this can illustrate my problem better.

Thanks!

![Scatter](https://user-images.githubusercontent.com/57306674/191410943-dac06f48-93b0-4886-acfc-26c431ac866d.jpg)

**Comment by wkjarosz** [comment]
Avoiding floating point precision issues is difficult and imperfect. Pushing off from the surface is an alternate strategy. It can work better in some cases, and worse in others. In both cases, yes, the length of the ray direction (or normal) would affect things. 

For the sphere, you can improve precision considerably by performing intermediate calculations (solving the quadratic equation) using doubles.  There are also other tricks to improve numerical further. The PBRT book discusses a few more if you are interested.

**Comment by zznewclear13** [comment]
Thanks for your reply! I added `pHit *= radius / Distance(pHit, Point3f(0, 0, 0));` to my calculations as pbrt book says, and normalized the direction of scattered ray. That gives me a perfectly clean result (still may have some acne that I don't notice)!
